# Generated by Django 6.0.6 on 2026-06-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
