# Generated by Django 6.0.6 on 2026-06-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blog_likes_comment_liked_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
